name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: aravinddharla/mongodb:4.0.0 # docker build -t aravinddharla/mongodb:4.0.0 .
    container_name: mongodb # docker run -d --name mongodb aravinddharla/mongodb:4.0.0
    volumes:
    - mongodb:/data/db # mongodb stores data in /data/db directory
  catalogue:
     build: ./catalogue
     image: aravinddharla/catalogue:4.0.0
     container_name: catalogue
     depends_on:
     - mongodb    
  frontend:
    build: ./frontend
    image: aravinddharla/frontend:4.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
  cart:
    build: ./cart
    image: aravinddharla/cart:4.0.0
    container_name: cart
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
      CATALOGUE_PORT: 8080
    depends_on:
    - catalogue
  redis:
    image: redis:7
    container_name: redis # docker run -d --name redis --network roboshop redis:7
    volumes:
    - redis:/data  
     
  user:
    build: ./user
    image: aravinddharla/user:4.0.0
    container_name: user
    environment:
      MONGO: true
      REDIS_URL: 'redis://redis:6379'
      MONGO_URL: "mongodb://mongodb:27017/users"
    depends_on:
    - mongodb



networks:
  default: # this means all the services in this file use this network
    name: roboshop
    driver: bridge
    external: false # if true it should be created manually, if false docker creates this network  
volumes:
  mongodb: # this volume is used by mongodb service to store data    
  catalogue:
  cart:
  user:

